import mgear.core.pyqt as gqt
QtGui, QtCore, QtWidgets, wrapInstance = gqt.qt_import()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(268, 699)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.ikfk_label = QtWidgets.QLabel(self.groupBox)
        self.ikfk_label.setObjectName("ikfk_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ikfk_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ikfk_slider = QtWidgets.QSlider(self.groupBox)
        self.ikfk_slider.setMinimumSize(QtCore.QSize(0, 15))
        self.ikfk_slider.setMaximum(100)
        self.ikfk_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ikfk_slider.setObjectName("ikfk_slider")
        self.horizontalLayout_3.addWidget(self.ikfk_slider)
        self.ikfk_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.ikfk_spinBox.setMaximum(100)
        self.ikfk_spinBox.setObjectName("ikfk_spinBox")
        self.horizontalLayout_3.addWidget(self.ikfk_spinBox)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.maxStretch_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxStretch_label.sizePolicy().hasHeightForWidth())
        self.maxStretch_label.setSizePolicy(sizePolicy)
        self.maxStretch_label.setObjectName("maxStretch_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.maxStretch_label)
        self.maxStretch_spinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxStretch_spinBox.sizePolicy().hasHeightForWidth())
        self.maxStretch_spinBox.setSizePolicy(sizePolicy)
        self.maxStretch_spinBox.setMinimum(1.0)
        self.maxStretch_spinBox.setProperty("value", 1.5)
        self.maxStretch_spinBox.setObjectName("maxStretch_spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maxStretch_spinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.divisions_label = QtWidgets.QLabel(self.groupBox)
        self.divisions_label.setObjectName("divisions_label")
        self.horizontalLayout.addWidget(self.divisions_label)
        self.div0_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.div0_spinBox.setMinimum(0)
        self.div0_spinBox.setProperty("value", 2)
        self.div0_spinBox.setObjectName("div0_spinBox")
        self.horizontalLayout.addWidget(self.div0_spinBox)
        self.div1_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.div1_spinBox.setMinimum(0)
        self.div1_spinBox.setProperty("value", 2)
        self.div1_spinBox.setObjectName("div1_spinBox")
        self.horizontalLayout.addWidget(self.div1_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.ikTR_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.ikTR_checkBox.setObjectName("ikTR_checkBox")
        self.verticalLayout.addWidget(self.ikTR_checkBox)
        self.mirrorIK_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.mirrorIK_checkBox.setObjectName("mirrorIK_checkBox")
        self.verticalLayout.addWidget(self.mirrorIK_checkBox)
        self.mirrorMid_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.mirrorMid_checkBox.setObjectName("mirrorMid_checkBox")
        self.verticalLayout.addWidget(self.mirrorMid_checkBox)
        self.extraTweak_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.extraTweak_checkBox.setObjectName("extraTweak_checkBox")
        self.verticalLayout.addWidget(self.extraTweak_checkBox)
        self.supportJoints_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.supportJoints_checkBox.setChecked(True)
        self.supportJoints_checkBox.setObjectName("supportJoints_checkBox")
        self.verticalLayout.addWidget(self.supportJoints_checkBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.squashStretchProfile_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.squashStretchProfile_pushButton.setObjectName("squashStretchProfile_pushButton")
        self.horizontalLayout_2.addWidget(self.squashStretchProfile_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        # Primaries
        self.primaries_groupBox = QtWidgets.QGroupBox(Form)
        self.primaries_groupBox.setObjectName("primaries_groupBox")
        self.primaries_gridLayout = QtWidgets.QGridLayout(self.primaries_groupBox)
        self.primaries_gridLayout.setObjectName("primaries_gridLayout")
        self.primaries_verticalLayout = QtWidgets.QVBoxLayout()
        self.primaries_verticalLayout.setObjectName("primaries_verticalLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.primaries_label = QtWidgets.QLabel(self.primaries_groupBox)
        self.primaries_label.setObjectName("primaries_label")
        self.horizontalLayout_1.addWidget(self.primaries_label)
        self.primaries_spinBox = QtWidgets.QSpinBox(self.primaries_groupBox)
        self.primaries_spinBox.setMinimum(0)
        self.primaries_spinBox.setProperty("value", 8)
        self.primaries_spinBox.setObjectName("primaries_spinBox")
        self.horizontalLayout_1.addWidget(self.primaries_spinBox)

        self.pPoints_label = QtWidgets.QLabel(self.primaries_groupBox)
        self.horizontalLayout_1.addWidget(self.pPoints_label)
        self.pPoints_spinBox = QtWidgets.QSpinBox(self.primaries_groupBox)
        self.pPoints_spinBox.setMinimum(3)
        self.pPoints_spinBox.setProperty("value", 5)
        self.pPoints_spinBox.setObjectName("pPoints_spinBox")
        self.horizontalLayout_1.addWidget(self.pPoints_spinBox)

        self.pJoints_label = QtWidgets.QLabel(self.primaries_groupBox)
        self.horizontalLayout_1.addWidget(self.pJoints_label)
        self.pJoints_spinBox = QtWidgets.QSpinBox(self.primaries_groupBox)
        self.pJoints_spinBox.setMinimum(2)
        self.pJoints_spinBox.setProperty("value", 4)
        self.pJoints_spinBox.setObjectName("pJoints_spinBox")
        self.horizontalLayout_1.addWidget(self.pJoints_spinBox)

        self.primaries_verticalLayout.addLayout(self.horizontalLayout_1)
        self.primaries_gridLayout.addLayout(self.primaries_verticalLayout, 0, 0, 1, 1)

        # pCoverts
        self.pCoverts_checkBox = QtWidgets.QCheckBox(self.primaries_groupBox)
        self.pCoverts_checkBox.setObjectName("pCoverts_checkBox")
        self.pCoverts_verticalLayout = QtWidgets.QVBoxLayout()
        self.pCoverts_verticalLayout.setObjectName("pCoverts_verticalLayout")
        self.pCoverts_verticalLayout.addWidget(self.pCoverts_checkBox)
        self.pCoverts_horizontalLayout = QtWidgets.QHBoxLayout()
        self.pCoverts_horizontalLayout.setObjectName("pCoverts_horizontalLayout")
        self.pCoverts_label = QtWidgets.QLabel(self.primaries_groupBox)
        self.pCoverts_label.setObjectName("pCoverts_label")
        self.pCoverts_horizontalLayout.addWidget(self.pCoverts_label)
        self.pCoverts_slider = QtWidgets.QSlider(self.primaries_groupBox)
        self.pCoverts_slider.setMinimumSize(QtCore.QSize(0, 15))
        self.pCoverts_slider.setMaximum(100)
        self.pCoverts_slider.setOrientation(QtCore.Qt.Horizontal)
        self.pCoverts_slider.setObjectName("pCoverts_slider")
        self.pCoverts_horizontalLayout.addWidget(self.pCoverts_slider)
        self.pCoverts_spinBox = QtWidgets.QSpinBox(self.primaries_groupBox)
        self.pCoverts_spinBox.setMaximum(100)
        self.pCoverts_spinBox.setObjectName("pCoverts_spinBox")
        self.pCoverts_horizontalLayout.addWidget(self.pCoverts_spinBox)
        self.pCoverts_verticalLayout.addLayout(self.pCoverts_horizontalLayout)
        self.pCoverts_horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.pCoverts_horizontalLayout2.setObjectName("pCoverts_horizontalLayout2")

        self.pCovertsPoints_label = QtWidgets.QLabel(self.primaries_groupBox)
        self.pCoverts_horizontalLayout2.addWidget(self.pCovertsPoints_label)
        self.pCovertsPoints_spinBox = QtWidgets.QSpinBox(self.primaries_groupBox)
        self.pCovertsPoints_spinBox.setMinimum(3)
        self.pCovertsPoints_spinBox.setProperty("value", 3)
        self.pCovertsPoints_spinBox.setObjectName("pCovertsPoints_spinBox")
        self.pCoverts_horizontalLayout2.addWidget(self.pCovertsPoints_spinBox)
        
        self.pCovertsJoints_label = QtWidgets.QLabel(self.primaries_groupBox)
        self.pCoverts_horizontalLayout2.addWidget(self.pCovertsJoints_label)
        self.pCovertsJoints_spinBox = QtWidgets.QSpinBox(self.primaries_groupBox)
        self.pCovertsJoints_spinBox.setMinimum(3)
        self.pCovertsJoints_spinBox.setProperty("value", 3)
        self.pCovertsJoints_spinBox.setObjectName("pCovertsJoints_spinBox")
        self.pCoverts_horizontalLayout2.addWidget(self.pCovertsJoints_spinBox)

        self.pCoverts_verticalLayout.addLayout(self.pCoverts_horizontalLayout2)

        self.primaries_gridLayout.addLayout(self.pCoverts_verticalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.primaries_groupBox, 1, 0, 1, 1)
        
        
        
        # Secondaries
        self.secondaries_groupBox = QtWidgets.QGroupBox(Form)
        self.secondaries_groupBox.setObjectName("secondaries_groupBox")
        self.secondaries_gridLayout = QtWidgets.QGridLayout(self.secondaries_groupBox)
        self.secondaries_gridLayout.setObjectName("secondaries_gridLayout")
        self.secondaries_verticalLayout = QtWidgets.QVBoxLayout()
        self.secondaries_verticalLayout.setObjectName("secondaries_verticalLayout")
        self.secondaries_horizontalLayout = QtWidgets.QHBoxLayout()
        self.secondaries_horizontalLayout.setObjectName("secondaries_horizontalLayout")
        self.secondaries_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.secondaries_label.setObjectName("secondaries_label")
        self.secondaries_horizontalLayout.addWidget(self.secondaries_label)
        self.secondaries_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.secondaries_spinBox.setMinimum(0)
        self.secondaries_spinBox.setProperty("value", 8)
        self.secondaries_spinBox.setObjectName("secondaries_spinBox")
        self.secondaries_horizontalLayout.addWidget(self.secondaries_spinBox)

        self.sPoints_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.secondaries_horizontalLayout.addWidget(self.sPoints_label)
        self.sPoints_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.sPoints_spinBox.setMinimum(3)
        self.sPoints_spinBox.setProperty("value", 5)
        self.sPoints_spinBox.setObjectName("sPoints_spinBox")
        self.secondaries_horizontalLayout.addWidget(self.sPoints_spinBox)

        self.sJoints_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.secondaries_horizontalLayout.addWidget(self.sJoints_label)
        self.sJoints_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.sJoints_spinBox.setMinimum(2)
        self.sJoints_spinBox.setProperty("value", 4)
        self.sJoints_spinBox.setObjectName("sJoints_spinBox")
        self.secondaries_horizontalLayout.addWidget(self.sJoints_spinBox)

        self.secondaries_verticalLayout.addLayout(self.secondaries_horizontalLayout)
        self.secondaries_gridLayout.addLayout(self.secondaries_verticalLayout, 0, 0, 1, 1)

        # sCoverts
        self.sCoverts_checkBox = QtWidgets.QCheckBox(self.secondaries_groupBox)
        self.sCoverts_checkBox.setObjectName("sCoverts_checkBox")
        self.sCoverts_verticalLayout = QtWidgets.QVBoxLayout()
        self.sCoverts_verticalLayout.setObjectName("sCoverts_verticalLayout")
        self.sCoverts_verticalLayout.addWidget(self.sCoverts_checkBox)
        self.sCoverts_horizontalLayout = QtWidgets.QHBoxLayout()
        self.sCoverts_horizontalLayout.setObjectName("sCoverts_horizontalLayout")
        self.sCoverts_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.sCoverts_label.setObjectName("sCoverts_label")
        self.sCoverts_horizontalLayout.addWidget(self.sCoverts_label)
        self.sCoverts_slider = QtWidgets.QSlider(self.secondaries_groupBox)
        self.sCoverts_slider.setMinimumSize(QtCore.QSize(0, 15))
        self.sCoverts_slider.setMaximum(100)
        self.sCoverts_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sCoverts_slider.setObjectName("sCoverts_slider")
        self.sCoverts_horizontalLayout.addWidget(self.sCoverts_slider)
        self.sCoverts_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.sCoverts_spinBox.setMaximum(100)
        self.sCoverts_spinBox.setObjectName("sCoverts_spinBox")
        self.sCoverts_horizontalLayout.addWidget(self.sCoverts_spinBox)
        self.sCoverts_verticalLayout.addLayout(self.sCoverts_horizontalLayout)
        self.sCoverts_horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.sCoverts_horizontalLayout2.setObjectName("sCoverts_horizontalLayout2")

        self.sCovertsPoints_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.sCoverts_horizontalLayout2.addWidget(self.sCovertsPoints_label)
        self.sCovertsPoints_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.sCovertsPoints_spinBox.setMinimum(3)
        self.sCovertsPoints_spinBox.setProperty("value", 3)
        self.sCovertsPoints_spinBox.setObjectName("sCovertsPoints_spinBox")
        self.sCoverts_horizontalLayout2.addWidget(self.sCovertsPoints_spinBox)
        
        self.sCovertsJoints_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.sCoverts_horizontalLayout2.addWidget(self.sCovertsJoints_label)
        self.sCovertsJoints_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.sCovertsJoints_spinBox.setMinimum(3)
        self.sCovertsJoints_spinBox.setProperty("value", 3)
        self.sCovertsJoints_spinBox.setObjectName("sCovertsJoints_spinBox")
        self.sCoverts_horizontalLayout2.addWidget(self.sCovertsJoints_spinBox)

        self.sCoverts_verticalLayout.addLayout(self.sCoverts_horizontalLayout2)

        self.secondaries_gridLayout.addLayout(self.sCoverts_verticalLayout, 1, 0, 1, 1)
        
        # sMarginals
        self.sMarginals_checkBox = QtWidgets.QCheckBox(self.secondaries_groupBox)
        self.sMarginals_checkBox.setObjectName("sMarginals_checkBox")
        self.sMarginals_verticalLayout = QtWidgets.QVBoxLayout()
        self.sMarginals_verticalLayout.setObjectName("sMarginals_verticalLayout")
        self.sMarginals_verticalLayout.addWidget(self.sMarginals_checkBox)
        self.sMarginals_horizontalLayout = QtWidgets.QHBoxLayout()
        self.sMarginals_horizontalLayout.setObjectName("sMarginals_horizontalLayout")
        self.sMarginals_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.sMarginals_label.setObjectName("sMarginals_label")
        self.sMarginals_horizontalLayout.addWidget(self.sMarginals_label)
        self.sMarginals_slider = QtWidgets.QSlider(self.secondaries_groupBox)
        self.sMarginals_slider.setMinimumSize(QtCore.QSize(0, 15))
        self.sMarginals_slider.setMaximum(100)
        self.sMarginals_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sMarginals_slider.setObjectName("sMarginals_slider")
        self.sMarginals_horizontalLayout.addWidget(self.sMarginals_slider)
        self.sMarginals_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.sMarginals_spinBox.setMaximum(100)
        self.sMarginals_spinBox.setObjectName("sMarginals_spinBox")
        self.sMarginals_horizontalLayout.addWidget(self.sMarginals_spinBox)
        self.sMarginals_verticalLayout.addLayout(self.sMarginals_horizontalLayout)
        self.sMarginals_horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.sMarginals_horizontalLayout2.setObjectName("sMarginals_horizontalLayout2")

        self.sMarginalsPoints_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.sMarginals_horizontalLayout2.addWidget(self.sMarginalsPoints_label)
        self.sMarginalsPoints_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.sMarginalsPoints_spinBox.setMinimum(3)
        self.sMarginalsPoints_spinBox.setProperty("value", 3)
        self.sMarginalsPoints_spinBox.setObjectName("sMarginalsPoints_spinBox")
        self.sMarginals_horizontalLayout2.addWidget(self.sMarginalsPoints_spinBox)
        
        self.sMarginalsJoints_label = QtWidgets.QLabel(self.secondaries_groupBox)
        self.sMarginals_horizontalLayout2.addWidget(self.sMarginalsJoints_label)
        self.sMarginalsJoints_spinBox = QtWidgets.QSpinBox(self.secondaries_groupBox)
        self.sMarginalsJoints_spinBox.setMinimum(3)
        self.sMarginalsJoints_spinBox.setProperty("value", 3)
        self.sMarginalsJoints_spinBox.setObjectName("sMarginalsJoints_spinBox")
        self.sMarginals_horizontalLayout2.addWidget(self.sMarginalsJoints_spinBox)

        self.sMarginals_verticalLayout.addLayout(self.sMarginals_horizontalLayout2)

        self.secondaries_gridLayout.addLayout(self.sMarginals_verticalLayout, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.secondaries_groupBox, 2, 0, 1, 1)




        self.ikRefArray_groupBox = QtWidgets.QGroupBox(Form)
        self.ikRefArray_groupBox.setObjectName("ikRefArray_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ikRefArray_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ikRefArray_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ikRefArray_horizontalLayout.setObjectName("ikRefArray_horizontalLayout")
        self.ikRefArray_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_1.setObjectName("ikRefArray_verticalLayout_1")
        self.ikRefArray_listWidget = QtWidgets.QListWidget(self.ikRefArray_groupBox)
        self.ikRefArray_listWidget.setDragDropOverwriteMode(True)
        self.ikRefArray_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.ikRefArray_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.ikRefArray_listWidget.setAlternatingRowColors(True)
        self.ikRefArray_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ikRefArray_listWidget.setSelectionRectVisible(False)
        self.ikRefArray_listWidget.setObjectName("ikRefArray_listWidget")
        self.ikRefArray_verticalLayout_1.addWidget(self.ikRefArray_listWidget)
        self.ikRefArray_copyRef_pushButton = QtWidgets.QPushButton(self.ikRefArray_groupBox)
        self.ikRefArray_copyRef_pushButton.setObjectName("ikRefArray_copyRef_pushButton")
        self.ikRefArray_verticalLayout_1.addWidget(self.ikRefArray_copyRef_pushButton)
        self.ikRefArray_horizontalLayout.addLayout(self.ikRefArray_verticalLayout_1)
        self.ikRefArray_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_2.setObjectName("ikRefArray_verticalLayout_2")
        self.ikRefArrayAdd_pushButton = QtWidgets.QPushButton(self.ikRefArray_groupBox)
        self.ikRefArrayAdd_pushButton.setObjectName("ikRefArrayAdd_pushButton")
        self.ikRefArray_verticalLayout_2.addWidget(self.ikRefArrayAdd_pushButton)
        self.ikRefArrayRemove_pushButton = QtWidgets.QPushButton(self.ikRefArray_groupBox)
        self.ikRefArrayRemove_pushButton.setObjectName("ikRefArrayRemove_pushButton")
        self.ikRefArray_verticalLayout_2.addWidget(self.ikRefArrayRemove_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ikRefArray_verticalLayout_2.addItem(spacerItem)
        self.ikRefArray_horizontalLayout.addLayout(self.ikRefArray_verticalLayout_2)
        self.gridLayout_3.addLayout(self.ikRefArray_horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ikRefArray_groupBox, 3, 0, 1, 1)
        self.upvRefArray_groupBox = QtWidgets.QGroupBox(Form)
        self.upvRefArray_groupBox.setObjectName("upvRefArray_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.upvRefArray_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.upvRefArray_horizontalLayout = QtWidgets.QHBoxLayout()
        self.upvRefArray_horizontalLayout.setObjectName("upvRefArray_horizontalLayout")
        self.upvRefArray_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.upvRefArray_verticalLayout_1.setObjectName("upvRefArray_verticalLayout_1")
        self.upvRefArray_listWidget = QtWidgets.QListWidget(self.upvRefArray_groupBox)
        self.upvRefArray_listWidget.setDragDropOverwriteMode(True)
        self.upvRefArray_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.upvRefArray_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.upvRefArray_listWidget.setAlternatingRowColors(True)
        self.upvRefArray_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.upvRefArray_listWidget.setSelectionRectVisible(False)
        self.upvRefArray_listWidget.setObjectName("upvRefArray_listWidget")
        self.upvRefArray_verticalLayout_1.addWidget(self.upvRefArray_listWidget)
        self.upvRefArray_copyRef_pushButton = QtWidgets.QPushButton(self.upvRefArray_groupBox)
        self.upvRefArray_copyRef_pushButton.setObjectName("upvRefArray_copyRef_pushButton")
        self.upvRefArray_verticalLayout_1.addWidget(self.upvRefArray_copyRef_pushButton)
        self.upvRefArray_horizontalLayout.addLayout(self.upvRefArray_verticalLayout_1)
        self.upvRefArray_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.upvRefArray_verticalLayout_2.setObjectName("upvRefArray_verticalLayout_2")
        self.upvRefArrayAdd_pushButton = QtWidgets.QPushButton(self.upvRefArray_groupBox)
        self.upvRefArrayAdd_pushButton.setObjectName("upvRefArrayAdd_pushButton")
        self.upvRefArray_verticalLayout_2.addWidget(self.upvRefArrayAdd_pushButton)
        self.upvRefArrayRemove_pushButton = QtWidgets.QPushButton(self.upvRefArray_groupBox)
        self.upvRefArrayRemove_pushButton.setObjectName("upvRefArrayRemove_pushButton")
        self.upvRefArray_verticalLayout_2.addWidget(self.upvRefArrayRemove_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.upvRefArray_verticalLayout_2.addItem(spacerItem1)
        self.upvRefArray_horizontalLayout.addLayout(self.upvRefArray_verticalLayout_2)
        self.gridLayout_5.addLayout(self.upvRefArray_horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.upvRefArray_groupBox, 4, 0, 1, 1)
        self.pinRefArray_groupBox = QtWidgets.QGroupBox(Form)
        self.pinRefArray_groupBox.setObjectName("pinRefArray_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pinRefArray_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pinRefArray_horizontalLayout = QtWidgets.QHBoxLayout()
        self.pinRefArray_horizontalLayout.setObjectName("pinRefArray_horizontalLayout")
        self.pinRefArray_verticalLayout = QtWidgets.QVBoxLayout()
        self.pinRefArray_verticalLayout.setObjectName("pinRefArray_verticalLayout")
        self.pinRefArray_listWidget = QtWidgets.QListWidget(self.pinRefArray_groupBox)
        self.pinRefArray_listWidget.setDragDropOverwriteMode(True)
        self.pinRefArray_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.pinRefArray_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.pinRefArray_listWidget.setAlternatingRowColors(True)
        self.pinRefArray_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.pinRefArray_listWidget.setSelectionRectVisible(False)
        self.pinRefArray_listWidget.setObjectName("pinRefArray_listWidget")
        self.pinRefArray_verticalLayout.addWidget(self.pinRefArray_listWidget)
        self.pinRefArray_copyRef_pushButton = QtWidgets.QPushButton(self.pinRefArray_groupBox)
        self.pinRefArray_copyRef_pushButton.setObjectName("pinRefArray_copyRef_pushButton")
        self.pinRefArray_verticalLayout.addWidget(self.pinRefArray_copyRef_pushButton)
        self.pinRefArray_horizontalLayout.addLayout(self.pinRefArray_verticalLayout)
        self.pinRefArray_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.pinRefArray_verticalLayout_2.setObjectName("pinRefArray_verticalLayout_2")
        self.pinRefArrayAdd_pushButton = QtWidgets.QPushButton(self.pinRefArray_groupBox)
        self.pinRefArrayAdd_pushButton.setObjectName("pinRefArrayAdd_pushButton")
        self.pinRefArray_verticalLayout_2.addWidget(self.pinRefArrayAdd_pushButton)
        self.pinRefArrayRemove_pushButton = QtWidgets.QPushButton(self.pinRefArray_groupBox)
        self.pinRefArrayRemove_pushButton.setObjectName("pinRefArrayRemove_pushButton")
        self.pinRefArray_verticalLayout_2.addWidget(self.pinRefArrayRemove_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.pinRefArray_verticalLayout_2.addItem(spacerItem2)
        self.pinRefArray_horizontalLayout.addLayout(self.pinRefArray_verticalLayout_2)
        self.gridLayout_4.addLayout(self.pinRefArray_horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.pinRefArray_groupBox, 5, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.ikfk_slider, QtCore.SIGNAL("sliderMoved(int)"), self.ikfk_spinBox.setValue)
        QtCore.QObject.connect(self.ikfk_spinBox, QtCore.SIGNAL("valueChanged(int)"), self.ikfk_slider.setValue)

        QtCore.QObject.connect(self.pCoverts_slider, QtCore.SIGNAL("sliderMoved(int)"), self.pCoverts_spinBox.setValue)
        QtCore.QObject.connect(self.pCoverts_spinBox, QtCore.SIGNAL("valueChanged(int)"), self.pCoverts_slider.setValue)

        QtCore.QObject.connect(self.sCoverts_slider, QtCore.SIGNAL("sliderMoved(int)"), self.sCoverts_spinBox.setValue)
        QtCore.QObject.connect(self.sCoverts_spinBox, QtCore.SIGNAL("valueChanged(int)"), self.sCoverts_slider.setValue)
        
        QtCore.QObject.connect(self.sMarginals_slider, QtCore.SIGNAL("sliderMoved(int)"), self.sMarginals_spinBox.setValue)
        QtCore.QObject.connect(self.sMarginals_spinBox, QtCore.SIGNAL("valueChanged(int)"), self.sMarginals_slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(gqt.fakeTranslate("Form", "Form", None, -1))
        self.ikfk_label.setText(gqt.fakeTranslate("Form", "IK/FK Blend", None, -1))
        self.maxStretch_label.setText(gqt.fakeTranslate("Form", "Max Stretch", None, -1))
        self.divisions_label.setText(gqt.fakeTranslate("Form", "Divisions", None, -1))

        self.primaries_groupBox.setTitle(gqt.fakeTranslate("Form", "Primary Feathers", None, -1))
        self.primaries_label.setText(gqt.fakeTranslate("Form", "Count", None, -1))
        self.pPoints_label.setText(gqt.fakeTranslate("Form", "Points", None, -1))
        self.pJoints_label.setText(gqt.fakeTranslate("Form", "Joints", None, -1))
        self.pCovertsPoints_label.setText(gqt.fakeTranslate("Form", "Points", None, -1))
        self.pCovertsJoints_label.setText(gqt.fakeTranslate("Form", "Joints", None, -1))
        self.pCoverts_checkBox.setText(gqt.fakeTranslate("Form", "Enable Coverts", None, -1))
        self.pCoverts_label.setText(gqt.fakeTranslate("Form", "Coverts Length", None, -1))

        self.secondaries_groupBox.setTitle(gqt.fakeTranslate("Form", "Secondary Feathers", None, -1))
        self.secondaries_label.setText(gqt.fakeTranslate("Form", "Count", None, -1))
        self.sPoints_label.setText(gqt.fakeTranslate("Form", "Points", None, -1))
        self.sJoints_label.setText(gqt.fakeTranslate("Form", "Joints", None, -1))
        self.sCovertsPoints_label.setText(gqt.fakeTranslate("Form", "Points", None, -1))
        self.sCovertsJoints_label.setText(gqt.fakeTranslate("Form", "Joints", None, -1))
        self.sCoverts_checkBox.setText(gqt.fakeTranslate("Form", "Enable Coverts", None, -1))
        self.sCoverts_label.setText(gqt.fakeTranslate("Form", "Coverts Length", None, -1))
        self.sMarginalsPoints_label.setText(gqt.fakeTranslate("Form", "Points", None, -1))
        self.sMarginalsJoints_label.setText(gqt.fakeTranslate("Form", "Joints", None, -1))
        self.sMarginals_checkBox.setText(gqt.fakeTranslate("Form", "Enable Marginals", None, -1))
        self.sMarginals_label.setText(gqt.fakeTranslate("Form", "Marginals Length", None, -1))

        self.ikTR_checkBox.setText(gqt.fakeTranslate("Form", "IK separated Trans and Rot ctl", None, -1))
        self.mirrorIK_checkBox.setToolTip(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.mirrorIK_checkBox.setStatusTip(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.mirrorIK_checkBox.setWhatsThis(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.mirrorIK_checkBox.setText(gqt.fakeTranslate("Form", "Mirror IK Ctl  axis behaviour", None, -1))
        self.mirrorMid_checkBox.setToolTip(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.mirrorMid_checkBox.setStatusTip(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.mirrorMid_checkBox.setWhatsThis(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.mirrorMid_checkBox.setText(gqt.fakeTranslate("Form", "MirrorMid Ctl and UPV  axis behaviour", None, -1))
        self.extraTweak_checkBox.setToolTip(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.extraTweak_checkBox.setStatusTip(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.extraTweak_checkBox.setWhatsThis(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.extraTweak_checkBox.setText(gqt.fakeTranslate("Form", "Add Extra Tweak Ctl", None, -1))
        self.supportJoints_checkBox.setToolTip(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.supportJoints_checkBox.setStatusTip(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.supportJoints_checkBox.setWhatsThis(gqt.fakeTranslate("Form", "This option set the axis of the mid CTL (elbow) and the up vector control to move in a mirror behaviour ", None, -1))
        self.supportJoints_checkBox.setText(gqt.fakeTranslate("Form", "Support Elbow Joints", None, -1))
        self.squashStretchProfile_pushButton.setText(gqt.fakeTranslate("Form", "Squash and Stretch Profile", None, -1))
        self.ikRefArray_groupBox.setTitle(gqt.fakeTranslate("Form", "IK Reference Array", None, -1))
        self.ikRefArray_copyRef_pushButton.setText(gqt.fakeTranslate("Form", "Copy from UpV Ref", None, -1))
        self.ikRefArrayAdd_pushButton.setText(gqt.fakeTranslate("Form", "<<", None, -1))
        self.ikRefArrayRemove_pushButton.setText(gqt.fakeTranslate("Form", ">>", None, -1))
        self.upvRefArray_groupBox.setTitle(gqt.fakeTranslate("Form", "UpV Reference Array", None, -1))
        self.upvRefArray_copyRef_pushButton.setText(gqt.fakeTranslate("Form", "Copy from IK Ref", None, -1))
        self.upvRefArrayAdd_pushButton.setText(gqt.fakeTranslate("Form", "<<", None, -1))
        self.upvRefArrayRemove_pushButton.setText(gqt.fakeTranslate("Form", ">>", None, -1))
        self.pinRefArray_groupBox.setTitle(gqt.fakeTranslate("Form", "Pin Elbow Reference Array", None, -1))
        self.pinRefArray_copyRef_pushButton.setText(gqt.fakeTranslate("Form", "Copy from IK Ref", None, -1))
        self.pinRefArrayAdd_pushButton.setText(gqt.fakeTranslate("Form", "<<", None, -1))
        self.pinRefArrayRemove_pushButton.setText(gqt.fakeTranslate("Form", ">>", None, -1))

